// src/components/SampleBooks.js
import React from "react";

export default function SampleBooks() {
  return (
    <section className="  text-gray-800 dark:text-white py-12 max-w-6xl mx-auto max-lg:px-4">
      <div className="container mx-auto text-center">
        <h2 className="text-3xl font-bold mb-8">
          Sample Books Generated by BookAI
        </h2>
        <div className="flex gap-12 items-center justify-around max-lg:flex-col">
          {/* Repeat similar blocks for each book */}

          <div class="book-sample transition-transform duration-[0.3s] ease-[ease] mb-10 p-5 rounded-[10px] bg-[#ffffff06]">
            <div
              class="w-[200px] h-[300px] bg-[url(https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png)] bgcenter  bg-[100%] flex justify-center items-center font-[bold] text-[color:var(--text-color)] text-lg text-center mt-0 mb-5 mx-auto p-2.5 rounded-[5px] background-size
"
              style={{ backgroundSize: "100%" }}
            ></div>
            <h3 className="font-bold">Science Fiction</h3>
            <p class="book-excerpt italic">
              "As Dr. Elara stepped through the shimmering portal, she knew
              there was no turning back. The fate of two universes now rested in
              her hands..."
            </p>
            <a href="/" class="read-more">
              Read More
            </a>
          </div>
          <div class="book-sample transition-transform duration-[0.3s] ease-[ease] mb-10 p-5 rounded-[10px] bg-[#ffffff06]">
            <div
              class="w-[200px] h-[300px] bg-[url(https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png)] bg-center flex justify-center items-center font-[bold] text-[color:var(--text-color)] text-lg text-center mt-0 mb-5 mx-auto p-2.5 rounded-[5px]"
              style={{ backgroundSize: "100%" }}
            ></div>
            <h3 className="font-bold">Mystery</h3>
            <p class="book-excerpt italic">
              "The old lighthouse stood silent, its beacon long extinguished.
              But on foggy nights, some swore they could still see its ghostly
              light..."
            </p>
            <a href="/" class="read-more">
              Read More
            </a>
          </div>
          <div class="book-sample transition-transform duration-[0.3s] ease-[ease] mb-10 p-5 rounded-[10px] bg-[#ffffff06]">
            <div
              class="book-cover-1  w-[200px] h-[300px] bg-[url(https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png)] bg-center flex justify-center items-center font-[bold] text-[color:var(--text-color)] text-lg text-center mt-0 mb-5 mx-auto p-2.5 rounded-[5px]"
              style={{ backgroundSize: "100%" }}
            ></div>
            <h3 className="font-bold">Fantasy</h3>
            <p class="book-excerpt italic">
              "The ancient prophecy spoke of a child born with starlight in
              their eyes. As the comet blazed overhead, the kingdom held its
              breath..."
            </p>
            <a href="/" class="read-more">
              Read More
            </a>
          </div>
          {/* Add more book blocks here */}
        </div>
      </div>
    </section>
  );
}
